name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Ensures that if you push a new commit, the previous stale run is cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-format-types-test:
    name: Lint, format check, typecheck & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # This automatically reads the "engines" field in package.json
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Check types
        run: npm run check-types

      - name: Audit dependencies
        run: npm run check-dependencies

      - name: Test
        run: npm run test
